/**
 * Inference engine for BayesianGPU
 *
 * This module provides the main `sample()` function that runs Bayesian inference
 * on a model specification using the WASM backend.
 *
 * Supports two backends:
 * - CPU (NdArray): Default, works everywhere
 * - WebGPU: GPU-accelerated, requires browser with WebGPU support
 *
 * @example
 * ```typescript
 * import { sample, initialize, Model, Beta, Binomial } from 'bayesiangpu';
 *
 * // Initialize with WebGPU if available
 * const backend = await initialize({ preferWebGPU: true });
 * console.log(`Using backend: ${backend}`);
 *
 * const model = new Model()
 *   .param('theta', Beta(1, 1))
 *   .observe(Binomial(100, 'theta'), [65])
 *   .build();
 *
 * const result = await sample(model, {
 *   numSamples: 1000,
 *   numChains: 4,
 * });
 *
 * console.log(result.diagnostics.rhat);
 * ```
 *
 * @module
 */

import type { ModelSpec } from './model';
import type { InferenceConfig, InferenceResult } from './result';

/**
 * Backend type for compute operations
 */
export type BackendType = 'cpu' | 'webgpu' | 'not_initialized';

/**
 * Options for initializing the WASM module
 */
export interface InitOptions {
  /** Prefer WebGPU if available (default: true with wgpu feature) */
  preferWebGPU?: boolean;
  /** Force CPU backend even if WebGPU is available */
  forceCPU?: boolean;
}

// Type declaration for the WASM module
// These will be generated by wasm-pack, but we declare them here for type safety
interface WasmModule {
  default: () => Promise<void>;
  run_inference: (modelJson: string, configJson: string) => string;
  version: () => string;
  // Backend functions (available with wgpu feature)
  init_backend?: () => Promise<string> | string;
  is_webgpu_available?: () => boolean;
  get_backend_type?: () => string;
}

// Module state
let wasmModule: WasmModule | null = null;
let initPromise: Promise<BackendType> | null = null;
let currentBackend: BackendType = 'not_initialized';

/**
 * Check if WebGPU is available in the current browser
 *
 * @returns true if WebGPU is available
 */
export function isWebGPUAvailable(): boolean {
  if (wasmModule?.is_webgpu_available) {
    return wasmModule.is_webgpu_available();
  }
  // Fallback check without WASM
  return typeof navigator !== 'undefined' && 'gpu' in navigator;
}

/**
 * Get the current compute backend type
 *
 * @returns Current backend: 'cpu', 'webgpu', or 'not_initialized'
 */
export function getBackendType(): BackendType {
  return currentBackend;
}

/**
 * Initialize the WASM module and compute backend
 *
 * This is called automatically by `sample()` if needed.
 * You can call it explicitly to:
 * - Pre-load the WASM module for faster first sample
 * - Control backend selection (CPU vs WebGPU)
 * - Check which backend will be used
 *
 * @param options - Initialization options
 * @returns Promise resolving to the backend type ('cpu' or 'webgpu')
 *
 * @example
 * ```typescript
 * // Auto-select best backend (WebGPU if available)
 * const backend = await initialize();
 *
 * // Force CPU backend
 * await initialize({ forceCPU: true });
 *
 * // Check before initializing
 * if (isWebGPUAvailable()) {
 *   console.log('WebGPU acceleration available!');
 * }
 * ```
 */
export async function initialize(options: InitOptions = {}): Promise<BackendType> {
  if (wasmModule && currentBackend !== 'not_initialized') {
    return currentBackend;
  }

  if (initPromise) {
    return initPromise;
  }

  initPromise = (async () => {
    try {
      // Dynamic import of the WASM module
      const module = await import('../pkg/bayesian_wasm.js') as unknown as WasmModule;
      await module.default();
      wasmModule = module;

      // Initialize backend
      if (options.forceCPU) {
        // Skip WebGPU initialization
        currentBackend = 'cpu';
        // Still call init_backend to set up CPU state
        if (module.init_backend) {
          await module.init_backend();
        }
      } else if (module.init_backend) {
        // wgpu feature is enabled - initialize async
        const result = await module.init_backend();
        const resultStr = typeof result === 'string' ? result : String(result);
        currentBackend = resultStr === 'webgpu' ? 'webgpu' : 'cpu';
      } else {
        // ndarray-only build - no init_backend function
        currentBackend = 'cpu';
      }

      return currentBackend;
    } catch (error) {
      initPromise = null;
      currentBackend = 'not_initialized';
      throw new Error(
        `Failed to initialize BayesianGPU WASM module: ${error instanceof Error ? error.message : String(error)}`
      );
    }
  })();

  return initPromise;
}

/**
 * Get the library version
 *
 * @returns Version string
 */
export async function getVersion(): Promise<string> {
  await initialize();
  return wasmModule!.version();
}

/**
 * Run Bayesian inference on a model
 *
 * This is the main entry point for running MCMC sampling. It:
 * 1. Initializes the WASM module if needed
 * 2. Serializes the model to JSON
 * 3. Runs NUTS sampling with the specified configuration
 * 4. Returns samples and diagnostics
 *
 * @param model - Model specification (from Model.build())
 * @param config - Inference configuration
 * @returns Inference result with samples and diagnostics
 *
 * @example
 * ```typescript
 * const result = await sample(model, {
 *   numSamples: 1000,
 *   numWarmup: 1000,
 *   numChains: 4,
 *   targetAccept: 0.8,
 *   seed: 42,
 * });
 * ```
 */
export async function sample(
  model: ModelSpec,
  config: InferenceConfig = {}
): Promise<InferenceResult> {
  // Ensure WASM is initialized
  await initialize();

  // Merge with defaults
  const mergedConfig: Required<InferenceConfig> = {
    numSamples: config.numSamples ?? 1000,
    numWarmup: config.numWarmup ?? 1000,
    numChains: config.numChains ?? 4,
    targetAccept: config.targetAccept ?? 0.8,
    seed: config.seed ?? Math.floor(Math.random() * 2 ** 32),
  };

  // Validate configuration
  if (mergedConfig.numSamples < 1) {
    throw new Error('numSamples must be at least 1');
  }
  if (mergedConfig.numWarmup < 0) {
    throw new Error('numWarmup must be non-negative');
  }
  if (mergedConfig.numChains < 1) {
    throw new Error('numChains must be at least 1');
  }
  if (mergedConfig.targetAccept <= 0 || mergedConfig.targetAccept >= 1) {
    throw new Error('targetAccept must be between 0 and 1 (exclusive)');
  }

  // Validate model
  if (!model.priors || model.priors.length === 0) {
    throw new Error('Model must have at least one parameter');
  }
  if (!model.likelihood) {
    throw new Error('Model must have a likelihood');
  }

  // Call WASM inference
  const modelJson = JSON.stringify(model);
  const configJson = JSON.stringify(mergedConfig);
  const resultJson = wasmModule!.run_inference(modelJson, configJson);

  // Parse result
  const result = JSON.parse(resultJson);

  // Check for errors from WASM
  if (result.error) {
    throw new Error(`Inference failed: ${result.error}`);
  }

  return result as InferenceResult;
}

/**
 * Quick sampling with sensible defaults
 *
 * Convenience function for quick exploration. Uses:
 * - 1000 samples, 1000 warmup
 * - 4 chains
 * - 0.8 target acceptance
 *
 * @param model - Model specification
 * @returns Inference result
 */
export async function quickSample(model: ModelSpec): Promise<InferenceResult> {
  return sample(model, {
    numSamples: 1000,
    numWarmup: 1000,
    numChains: 4,
    targetAccept: 0.8,
  });
}

/**
 * Production sampling with more samples
 *
 * For final analysis. Uses:
 * - 4000 samples, 2000 warmup
 * - 4 chains
 * - 0.9 target acceptance (for better adaptation)
 *
 * @param model - Model specification
 * @returns Inference result
 */
export async function productionSample(
  model: ModelSpec
): Promise<InferenceResult> {
  return sample(model, {
    numSamples: 4000,
    numWarmup: 2000,
    numChains: 4,
    targetAccept: 0.9,
  });
}

/**
 * Fast sampling for development
 *
 * For quick iteration. Uses:
 * - 200 samples, 100 warmup
 * - 2 chains
 *
 * @param model - Model specification
 * @returns Inference result
 */
export async function fastSample(model: ModelSpec): Promise<InferenceResult> {
  return sample(model, {
    numSamples: 200,
    numWarmup: 100,
    numChains: 2,
    targetAccept: 0.8,
  });
}
