# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_bayesiangpu_wrappers", use_symbols = TRUE, package_name = "bayesiangpu")

#' @docType package
#' @usage NULL
#' @useDynLib bayesiangpu, .registration = TRUE
NULL

normal_dist <- function(loc, scale) .Call(wrap__normal_dist, loc, scale)
half_normal_dist <- function(scale) .Call(wrap__half_normal_dist, scale)
half_cauchy_dist <- function(scale) .Call(wrap__half_cauchy_dist, scale)
beta_dist <- function(alpha, beta) .Call(wrap__beta_dist, alpha, beta)
gamma_dist <- function(shape, rate) .Call(wrap__gamma_dist, shape, rate)
uniform_dist <- function(low, high) .Call(wrap__uniform_dist, low, high)
exponential_dist <- function(rate) .Call(wrap__exponential_dist, rate)
cauchy_dist <- function(loc, scale) .Call(wrap__cauchy_dist, loc, scale)
student_t_dist <- function(df, loc, scale) .Call(wrap__student_t_dist, df, loc, scale)
log_normal_dist <- function(loc, scale) .Call(wrap__log_normal_dist, loc, scale)
bernoulli_dist <- function(p) .Call(wrap__bernoulli_dist, p)
binomial_dist <- function(n, p) .Call(wrap__binomial_dist, n, p)
poisson_dist <- function(rate) .Call(wrap__poisson_dist, rate)
multivariate_normal_dist <- function(mu, cov, scale_tril) .Call(wrap__multivariate_normal_dist, mu, cov, scale_tril)
dirichlet_dist <- function(alpha) .Call(wrap__dirichlet_dist, alpha)
multinomial_dist <- function(n, probs) .Call(wrap__multinomial_dist, n, probs)
laplace_dist <- function(loc, scale) .Call(wrap__laplace_dist, loc, scale)
logistic_dist <- function(loc, scale) .Call(wrap__logistic_dist, loc, scale)
inverse_gamma_dist <- function(alpha, beta) .Call(wrap__inverse_gamma_dist, alpha, beta)
chi_squared_dist <- function(df) .Call(wrap__chi_squared_dist, df)
truncated_normal_dist <- function(loc, scale, low, high) .Call(wrap__truncated_normal_dist, loc, scale, low, high)
weibull_dist <- function(shape, scale) .Call(wrap__weibull_dist, shape, scale)
pareto_dist <- function(alpha, x_m) .Call(wrap__pareto_dist, alpha, x_m)
gumbel_dist <- function(loc, scale) .Call(wrap__gumbel_dist, loc, scale)
half_student_t_dist <- function(df, scale) .Call(wrap__half_student_t_dist, df, scale)
negative_binomial_dist <- function(r, p) .Call(wrap__negative_binomial_dist, r, p)
categorical_dist <- function(probs) .Call(wrap__categorical_dist, probs)
geometric_dist <- function(p) .Call(wrap__geometric_dist, p)
discrete_uniform_dist <- function(low, high) .Call(wrap__discrete_uniform_dist, low, high)
beta_binomial_dist <- function(n, alpha, beta) .Call(wrap__beta_binomial_dist, n, alpha, beta)
zero_inflated_poisson_dist <- function(rate, zero_prob) .Call(wrap__zero_inflated_poisson_dist, rate, zero_prob)
zero_inflated_neg_binomial_dist <- function(r, p, zero_prob) .Call(wrap__zero_inflated_neg_binomial_dist, r, p, zero_prob)
hypergeometric_dist <- function(big_n, big_k, n) .Call(wrap__hypergeometric_dist, big_n, big_k, n)
ordered_logistic_dist <- function(eta, cutpoints) .Call(wrap__ordered_logistic_dist, eta, cutpoints)
run_nuts_sampling <- function(model_json, num_samples, num_warmup, num_chains, target_accept, seed) .Call(wrap__run_nuts_sampling, model_json, num_samples, num_warmup, num_chains, target_accept, seed)
run_advi <- function(model_json, method, num_iterations, num_samples, learning_rate, seed) .Call(wrap__run_advi, model_json, method, num_iterations, num_samples, learning_rate, seed)
